# Site settings
title: League of Legends @ Western Washington University
email: wwulov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Western Washington University's Official League of Legends eSports Organization
baseurl:
url: /
twitter_username: wwulol
# github_username:  jekyll

# Build settings
markdown: kramdown
